### ISSUE TITLE
[BUG] Tizen Xamarin.Forms.Init error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mono/SkiaSharp#1113]
```
System.TypeLoadException: Method 'LoadImageAsync' in type 'SkiaSharp.Views.Forms.SKImageSourceHandler' from assembly 'SkiaSharp.Views.Forms, Version=1.68.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Xamarin.Forms.Internals.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType)
   at Xamarin.Forms.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags)
   at Xamarin.Forms.Internals.Registrar.RegisterAll(Type[] attrTypes)
   at Xamarin.Forms.Forms.SetupInit(CoreApplication application, InitializationOptions options)
   at Xamarin.Forms.Forms.Init(CoreApplication application, Boolean useDeviceIndependentPixel)
```

latest nightly build XF
latest preview SkiaSharp

**Comment by mattleibow** [comment]
Thanks for reporting this. It appears that Tizen has changed some things in Forms. I got a fix.

**Comment by mattleibow** [comment]
So I just pushed a potential fix (#1117) to the preview feed: https://aka.ms/skiasharp-eap/index.json
The version is: 1.68.2-pr.1117.1

Let me know it that works - I can't test right now as I am having issues with the Tizen emulators, and my device got bust somehow. If it works, then we can merge. And, when 4.4 is more than a month old and people can update, then we can move permanently.

**Comment by VladislavAntonyuk** [comment]
@mattleibow I still see the issue:
![image](https://user-images.githubusercontent.com/33021114/73517052-0eac8780-4403-11ea-8930-8be64487502f.png)

**Comment by mattleibow** [comment]
Pity. I guess we are going to have to just use the latest forms. Not too bad I suppose.

**Comment by VladislavAntonyuk** [comment]
I would appreciate if you publish a potential fix before merging to the master, so I could give a fast feedback

**Comment by mattleibow** [comment]
Oh, will do. It is building as we speak!

**Comment by mattleibow** [comment]
Still having a look at this. The fix is easy, but UWP and CI aren't happy. Seems to be some issue with PDB files or something....

**Comment by VladislavAntonyuk** [comment]
with preview.39 I receive the same error, but on app.Run(args)
```
System.TypeLoadException: Method 'LoadImageAsync' in type 'SkiaSharp.Views.Forms.SKImageSourceHandler' from assembly 'SkiaSharp.Views.Forms, Version=1.68.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Xamarin.Forms.Internals.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType)
   at Xamarin.Forms.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags)
   at Xamarin.Forms.Forms.SetupInit(CoreApplication application, InitializationOptions options)
   at Xamarin.Forms.Forms.Init(CoreApplication application, Boolean useDeviceIndependentPixel)

```

**Comment by rookiejava** [comment]
Thank you for reporting the issue. As @mattleibow  mentioned above, there are small changes ([#9025](https://github.com/xamarin/Xamarin.Forms/pull/9025)) on XF.Tizen backend. I think updating Xamarin.Forms version to 4.5.0 or higher will solve this. Sorry for inconvenience. 🙏
