### ISSUE TITLE
Violates Windows Store App Certification

### ISSUE THREAD

**Issue by deanchalk** [mono/SkiaSharp#129]
running a UWP app through windows store certification kit and I get

**API getenv in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. libSkiaSharp.dll calls this API.**

So we cant publish UWP apps with SkiaSharp.

**Comment by migueldeicaza** [comment]
I suspect the problem is this code from:

skia/src/utils/SkRTConf.cpp

There is some code surrounded by `SK_BUILD_FOR_WINRT` and we are bringing this in.

**Comment by bholmes** [comment]
The SkRTConf.cpp preprocessor check appears to do the right thing.  It should be excluded.

I believe it is coming from libjpeg-turbo in the third party section.

https://skia.googlesource.com/third_party/libjpeg-turbo/+/debddedc75850bcdeb8a57258572f48b802a4bb3/simd/jsimd_x86_64.c#52

Trying to think of a clean way to patch those files.  @mattleibow have we patched any other third party work?

**Comment by mattleibow** [comment]
Fixed in commit c185f5cc2487728b0fa64fa25b57334292f5195d

**Comment by mattleibow** [comment]
Inject an empty method using defines. I am not sure how this compiled since the code in SkRTConf.cpp throws a compiler error, but the code in jsimd_x86_64.c does not...

**Comment by mattleibow** [comment]
This should be fixed in the upcoming (planned for this week) release: v1.53.1

**Comment by mattleibow** [comment]
Re-opening this on account that x86 still uses `getenv` somewhere. ARM and x64 appear to be fine.

**Comment by mattleibow** [comment]
I think everything is fixed now, just waiting on my app to be officially published.

**Comment by mattleibow** [comment]
> **Your submission for Skia.UWP.Demo passed certification.**
> 
> It will take up to 16 hours for your changes to be visible to all of your customers. Once published, your app's listing will be available at https://www.microsoft.com/store/apps/9NBLGGH51856. 
> 
> Thank you, 
> The Windows Store Team

**Comment by tseemann-xematec** [comment]
Hi guys

I am still experiencing this issue with SkiaSharp v1.54 :(

Message from Windows Store Certification:
**API getenv in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. libSkiaSharp.dll calls this API**

Any suggestions?

**Comment by mattleibow** [comment]
@tseemann-xematec That is weird. Especially since I have an app on the store using v1.54.0. What you can do to test is to run the cert tool on one platform at a time and see which one is failing.

What you can try is to remove the NuGet, and then delete it from your cache 
C:\Users\username\.nuget\packages\SkiaSharp

Then restore it. Maybe for some reason it is doing it wrong. I released the app using the NuGet, so it can't be the released one. But, just for sanity, could you re-download and then run the cert again?

Let me know what happens...

**Comment by tseemann-xematec** [comment]
Thanks, @mattleibow - I will try removing and re-adding the package entirely. I'll be back.

**Comment by mattleibow** [comment]
@tseemann-xematec Did this resolve your issue?

**Comment by tseemann-xematec** [comment]
@mattleibow Problem solved :) You were right - we still had a reference to v1.53. All our direct references in our projects to SkiaSharp were correctly v1.54, but it turned out we had an indirect reference to v1.53 in one of our own NuGet packages, because it stated a dependency on v1.53, even though it was itself using v1.54.

Thanks for your hint!
