### ISSUE TITLE
Setting SKPaint.IsStroke has no effect (1.53 regression)

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#135]
I'm seeing what seems like a regression bug. The following code (unless I'm missing something obvious) should not throw an exception:
```
using (SKPaint p = new SKPaint()) {
    p.IsStroke = false;
    if (p.IsStroke != false) {
        throw new Exception();
    }
}
```
But with SkiaSharp 1.53, I am seeing the exception thrown. When I downgrade to 1.49.1, the bug goes away (no exception thrown). This is on Win7 SP1 with VS 2015 Community Update 2, .NET framework 4.5.2.

**Comment by mattleibow** [comment]
I am not exactly sure why this this changed, since it is fixed in v1.53.1 - which is the same native code... And there has been no change in the managed part. I rolled back to this version and still was not able to reproduce the error... which technically is an impossibility... 

The only change I made was to update my VS 2015 from Update 2 to Update 3... I think this mush have resulted in a change in the compiler because this also happened: #114 

This code should not cause any issues since it is simply setting a field, and then fetching it.

In a summary: It is fixed in v1.53.1 (and if I recompile v1.53.0)

**Comment by tdenniston** [comment]
@mattleibow Weird! Were you able to reproduce it? I ask because it's such a strange looking bug that I wonder if there's something wrong with my environment.

**Comment by tdenniston** [comment]
@mattleibow Unfortunately, I'd like to reopen this issue. I just upgraded to VS Update 3 and SkiaSharp 1.53.1 and I still encounter this bug.

**Comment by mattleibow** [comment]
@tdenniston I am not too sure about this issue anymore... Basically, it happens on Windows, in Release mode - similar to the other issue...

The `IsStroke` property (on the C side) looks like this:

```cpp
bool sk_paint_is_stroke(const sk_paint_t* cpaint) {
    return AsPaint(*cpaint).getStyle() != SkPaint::kFill_Style;
}
```

Pretty simple... but once the value gets to the C# side, it has changed to `true`, no matter what. If I change the `bool` to an `int` on the C# side, the value is some huge number.... really weird. Another weird thing, if I change the `bool` to an `int` on the C side, then everything works. And, another... If I keep the `bool` on both C and C#, but flip the equals:

```cpp
bool sk_paint_is_stroke(const sk_paint_t* cpaint) {
    return AsPaint(*cpaint).getStyle() == SkPaint::kStroke_Style;
}
```

That also works... 💥 there goes my mind 😄 I think MS is shipping a dodgy optimizer. This is making me scared, so I am going to work around it by passing the value and doing the comparison in C#.

**Comment by mattleibow** [comment]
Confirmed that after the revert of the fix, the test failed. Re-applying the fix and the test should pass.

**Comment by mattleibow** [comment]
@tdenniston test are all passing, I will release a fix soon (today/tomorrow) Thanks for your help!

**Comment by mattleibow** [comment]
@tdenniston I pushed out a release that should work now: [v1.53.1.1](https://github.com/mono/SkiaSharp/releases/tag/v1.53.1.1)

**Comment by tdenniston** [comment]
@mattleibow Confirmed the bug is fixed! Thanks for getting to it so quickly.

I might have some time in the next few days to dig deeper into what's going on. I've tried to debug into native skia before without luck, as I can't seem to get VS to load the libSkiaSharp.dll symbols. You wouldn't happen to have any idea how to get that working?
