### ISSUE TITLE
System.DllNotFoundException: libSkiaSharp exception is thrown in Blazor WASM .NET 8.0

### ISSUE THREAD

**Issue by Akash26Arul** [mono/SkiaSharp#2745]
### Description
System.DllNotFoundException: libSkiaSharp exception is thrown while using SkiaSharp library in Blazor WASM .NET 8.0 and this issue doesn't occur in Blazor WASM .NET 6.0.

**Stack trace:**  

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. 
 ---> System.DllNotFoundException: libSkiaSharp 
    at SkiaSharp.SKImageInfo..cctor() 

**Note:** 
When trying the same approach in Blazor WASM .NET 6.0, there is no issues. 

### Code
```cs
try 
{ 
    using (SKBitmap bitmap = new SKBitmap(500, 500, SKImageInfo.PlatformColorType, SKAlphaType.Premul)) 
    { 
        using (SKSurface sKSurface = SKSurface.Create(bitmap.Info)) 
        { 
            SKCanvas sKCanvas = sKSurface.Canvas; 
            SKPaint sKPaint = new SKPaint(); 
            sKPaint.Color = new SKColor(255, 0, 0); 
            sKCanvas.DrawText("Blazor", new SKPoint(250, 250), sKPaint); 
            MemoryStream stream = new MemoryStream(); 
            sKSurface.Snapshot().Encode(SKEncodedImageFormat.Png, 100).SaveTo(stream); 
        } 
    } 
} 
catch (Exception ex) 
{ 
    ex.ToString(); 
} 
```

### Expected Behavior

Should draw the text and save as png. 

### Actual Behavior

Throws the above mentioned exception (System.DllNotFoundException: libSkiaSharp)

### Version of SkiaSharp

2.88.6

### Last Known Good Version of SkiaSharp

None

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

.NET 8.0

**ASP.NET Core .NET 8.0 :** Working fine

**Blazor server side .NET 8.0 :** Working fine

**Blazor client side (WASM) .NET 8.0 :** Facing Lib SkiaSharp issue

**Comment by Akash26Arul** [comment]
Hi team,

Any update on this?

Regards,
Akash.

**Comment by torourke55** [comment]
I was able to run your code after adding SkiaSharp.Views.Blazor package. https://www.nuget.org/packages/SkiaSharp.Views.Blazor/2.88.7. I'm using WASM .NET 8.0 Visual Studio 2022 version 17.9.1.

**Comment by mattleibow** [comment]
You need to either install `SkiaSharp.Views.Blazor` or `SkiaSharp.NativeAssets.WebAssembly` in order to get the binaries for WASM.

Try the latest versions as we have also fixed several packaging issues.

**Comment by gismofx** [comment]
> SkiaSharp.Views.Blazor

I'm getting the same issue. I tried the latest release and the latest preview release. 

I found a thread from a few years ago https://github.com/mono/SkiaSharp/issues/1725

Doing this is a work-around:
```xml
	<ItemGroup>
		<NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)\8.3.1-preview.1.2\*.a" />
	</ItemGroup>
```

**Comment by corradolab** [comment]
The error still happend to me with 2.0.0-rc5.1.

Visual Studio warned no native assemblies would be built because WasmBuildNative was false.
So I added `<PropertyGroup><WasmBuildNative>true</WasmBuildNative></PropertyGroup>` to the project file.

This triggered compilation error because `wasm-tools-net8` workload was missing.
I executed `dotnet workload restore` as suggested but the error remained.

I started Visual Studio Installer, switched to "Single components" and enabled ".NET 8.0 WebAssembly Build Tools" which fixed the issue.

**Comment by rafael-vasconcellos** [comment]
> The error still happend to me with 2.0.0-rc5.1.
> 
> Visual Studio warned no native assemblies would be built because WasmBuildNative was false. So I added `<PropertyGroup><WasmBuildNative>true</WasmBuildNative></PropertyGroup>` to the project file.
> 
> This triggered compilation error because `wasm-tools-net8` workload was missing. I executed `dotnet workload restore` as suggested but the error remained.
> 
> I started Visual Studio Installer, switched to "Single components" and enabled ".NET 8.0 WebAssembly Build Tools" which fixed the issue.

I'm building on a linux machine, what should I do?

**Comment by Dunge** [comment]
I also have the problem that my debug build on Windows by Visual Studio works, but not when building a docker image.

No difference between `SkiaSharp.Views.Blazor` or `SkiaSharp.NativeAssets.WebAssembly`, but I guess I'll use the later because I don't need the component.

Can anyone explain what <WasmBuildNative> actually do? It's not part of the Microsoft Learn website. Seems lengthen the build process. As with the previous user said, it then requested `wasm-tools`

I added this as part of my  `sdk:9.0 AS build` step:

`RUN dotnet workload install wasm-tools`
And it then complained about python. So I added
`RUN apt-get update && apt-get install -y python3 && rm -rf /var/lib/apt/lists/*`

And it finally worked!

My build time now increased from 5 minutes (which was already long) to 8 minutes 😭.

The documentation of this project could certainly use some guidance about this.
