### ISSUE TITLE
Exception using SkiaSharp compiled for Linux

### ISSUE THREAD

**Issue by jesanfafon** [mono/SkiaSharp#377]
When we attempt to construct a new SKBitmap on Ubuntu 17.04, we receive the following exception:

```
System.Exception: Unable to allocate pixels for the bitmap.
   at SkiaSharp.SKBitmap..ctor(SKImageInfo info, Int32 rowBytes)
```
We are using SkiaSharp 1.59.1 and Avalonia.Skia.Linux.Natives 1.57.1.4. 
I initially thought that we may have out of date dependencies or libraries, so I tried to compile SkiaSharp from source, but ran into a bunch of issues with Cake upgrading to .NET Framework 4.6 on all of their nuget packages and compilation issues building Skia. I'm stuck, on that front.

Any ideas what might be causing our exception, here?

**Comment by mattleibow** [comment]
Yes... the versions are out of sync. The 1.59.x SkiaSharp needs the m59 native files.
I have just fixed the cake issues, so you should be able to rebuild.

But, you might not have to. We have a linux build (not official yet), but you can still use it:
https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp-Linux/79/Azure/

More specifically: https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp-Linux/79/Azure/processDownloadRequest/ArtifactsFor-79/3c31bd5c5701a6eb3651110b4708bb1d0492c7fc/output/native/linux/x64/libSkiaSharp.so

You should be able to just include that file, and make sure it is copied to output. You can still use the NuGet form nuget.org, since that will only copy the managed bits. Let me know if this works.

**Comment by jesanfafon** [comment]
That worked! In trying to get Skia to build locally, I pulled the artifacts from the Jenkins server and got everything working locally. I still cannot build Skia from source, because the git hash referenced from SkiaSharp does not build locally (there are unused functions, and Werror is flagged), but I think this should do me for now.

Thank you for your help!

**Comment by jesanfafon** [comment]
Q: How does your Jenkins server build Skia successfully? I looked through everything I can see publicly and didn't see anything too magical. I've wound up commenting out the Werror flags in my local clone

**Comment by mattleibow** [comment]
How are you building SkiaSharp? I just run the `./bootstrapper.sh -t externals` and all builds. I am using Ubuntu 14.04 with `mono-complete` and `msbuild` installed. I am not too sure if there is anything else.

**Comment by mattleibow** [comment]
Just thinking about your errors, this is why I use an Ubuntu 14, because it comes with an old gcc. I think skia is compatible with gcc 4.8. For the newer versions, you will have to install this: `g++-4.8-multilib` and then run the build: 

    CC=gcc-4.8 CXX=g++-4.8 AR=gcc-ar-4.8 NM=gcc-nm-4.8 ./bootstrapper.sh -t everything

I put together a slightly old wiki: https://github.com/mono/SkiaSharp/wiki/Building-on-Linux

**Comment by mattleibow** [comment]
I am closing this issue as I think the issue here was the difference in the managed/native APIs. The solution is to either build skia yourself, or use the semi-official link attached to each release.

**Comment by nelhit** [comment]
hi i have the same problem, i dowload the from libSkiaSharp.so https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp-Linux/79/Azure/processDownloadRequest/ArtifactsFor-79/3c31bd5c5701a6eb3651110b4708bb1d0492c7fc/output/native/linux/x64/libSkiaSharp.so. 

My project is a net core 2.1 project, I include the library into my project with property "copy always" and alse in my startup.cs, i put **context.LoadUnmanagedLibrary(Path.Combine(Directory.GetCurrentDirectory(), "libSkiaSharp.so"))** and i got error:

_**Unable to allocate pixels for the bitmap., at SkiaSharp.SKBitmap..ctor(SKImageInfo info, Int32 rowBytes) at SkiaSharp.SKBitmap..ctor(SKImageInfo info) at SkiaSharp.SKBitmap.Decode(SKCodec codec, SKImageInfo bitmapInfo) at SkiaSharp.SKBitmap.Decode(SKCodec codec) at SkiaSharp.SKBitmap.Decode(Stream stream)**_

My deploy machine is an amazon with OS CentOS Linux 7 (Core). I installed libgdiplus and also i install mono-complete.

I appreciate your help if i need install someting else. I dont know what else i need to install.

**Comment by mattleibow** [comment]
That looks like a different error: "Unable to allocate pixels for the bitmap."

It appears that for some reason, SkiaSharp was not able to allocate pixels. This could be that either the dimensions were too large for the memory (which is probably not the case), too small. Are you able to create a new issue with the image attached so I can follow up there?
